/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'bg': '#1F2128',
        'bg-gradient-top': '#23252D',
        'bg-gradient-bottom': '#1B1D23',
        'surface': '#2A2D35',
        'surface-dim': '#252830',
        'surface-hover': '#32353D',
        'border-subtle': '#3A3D45',
        'border-light': '#454850',
        'accent': '#59F6FF',
        'accent-dim': '#3AA8B0',
        'accent-orange': '#59F6FF',
        'success': '#4ADE80',
        'warning': '#FBBF24',
        'error': '#F87171',
        'ai': '#B388FF',
        'inactive': '#5A6070',
        'text-primary': '#E0E4EC',
        'text-muted': '#8B91A0',
        'text-dim': '#5A6070',
      },
      fontFamily: {
        heading: ['Space Grotesk', 'system-ui', 'sans-serif'],
        body: ['IBM Plex Sans', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        mono: ['IBM Plex Mono', 'Fira Code', 'monospace'],
      },
      spacing: {
        'sidebar': '48px',
        'sidebar-expanded': '200px',
        'panel': '380px',
      },
      transitionDuration: {
        'micro': '120ms',
        'selection': '150ms',
        'panel': '250ms',
        'camera': '650ms',
        'node': '400ms',
        'layout': '800ms',
      },
      transitionTimingFunction: {
        'ease-out-quart': 'cubic-bezier(0.25, 1, 0.5, 1)',
        'ease-out-quint': 'cubic-bezier(0.22, 1, 0.36, 1)',
        'ease-out-expo': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'ease-in-out-quint': 'cubic-bezier(0.83, 0, 0.17, 1)',
        'ease-in-out-expo': 'cubic-bezier(0.87, 0, 0.13, 1)',
      },
      animation: {
        'fade-in': 'fadeIn 150ms ease-out',
        'slide-in-right': 'slideInRight 250ms cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-in-left': 'slideInLeft 250ms cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-up': 'slideUp 150ms ease-out',
        'pulse': 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'shimmer': 'shimmer 1.5s ease-in-out infinite',
      },
      zIndex: {
        'graph': '0',
        'minimap': '10',
        'sidebar': '20',
        'panel': '30',
        'command-palette': '40',
        'toast': '50',
        'tooltip': '60',
        'telemetry': '15',
        'context-menu': '70',
      },
    },
  },
  plugins: [],
}
