/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'bg-deep': '#0D0D0D',
        'bg-surface': '#151515',
        'bg-surface-dim': '#111111',
        'bg-surface-hover': '#1A1A1A',
        'border-subtle': '#222222',
        'border-light': '#333333',
        'accent-orange': '#E65100',
        'accent-orange-dim': '#BF360C',
        'accent-orange-glow': '#FF6D00',
        'accent-cyan': '#00E5FF',
        'accent-cyan-dim': '#00B8D4',
        'accent-success': '#00E676',
        'accent-error': '#FF1744',
        'accent-ai': '#B388FF',
        'accent-inactive': '#555555',
        'accent-warning': '#FFD740',
        'text-primary': '#F0F0F0',
        'text-muted': '#888888',
        'text-dim': '#555555',
      },
      fontFamily: {
        heading: ['Space Grotesk', 'system-ui', 'sans-serif'],
        body: ['IBM Plex Sans', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        mono: ['IBM Plex Mono', 'Fira Code', 'monospace'],
      },
      spacing: {
        'sidebar': '48px',
        'sidebar-expanded': '200px',
        'panel': '380px',
      },
      transitionDuration: {
        'micro': '120ms',
        'selection': '150ms',
        'panel': '250ms',
        'camera': '650ms',
        'node': '400ms',
        'layout': '800ms',
      },
      transitionTimingFunction: {
        'ease-out-quart': 'cubic-bezier(0.25, 1, 0.5, 1)',
        'ease-out-quint': 'cubic-bezier(0.22, 1, 0.36, 1)',
        'ease-out-expo': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'ease-in-out-quint': 'cubic-bezier(0.83, 0, 0.17, 1)',
        'ease-in-out-expo': 'cubic-bezier(0.87, 0, 0.13, 1)',
      },
      animation: {
        'fade-in': 'fadeIn 150ms ease-out',
        'slide-in-right': 'slideInRight 250ms cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-in-left': 'slideInLeft 250ms cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-up': 'slideUp 150ms ease-out',
        'pulse': 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'shimmer': 'shimmer 1.5s ease-in-out infinite',
      },
      zIndex: {
        'graph': '0',
        'minimap': '10',
        'sidebar': '20',
        'panel': '30',
        'command-palette': '40',
        'toast': '50',
        'tooltip': '60',
        'telemetry': '15',
      },
    },
  },
  plugins: [],
}
