# Fetch tree-sitter language grammars from upstream repos.
# Each grammar compiles to a C static library exporting tree_sitter_{lang}().
#
# Grammars are generated by a specific tree-sitter CLI version and need
# the corresponding parser.h / internal headers from that version.

set(GRAMMAR_DIR "${CMAKE_CURRENT_BINARY_DIR}/grammars")

# Download internal headers (parser.h, array.h, etc.) for a specific
# tree-sitter version. Stores them under include/<ver>/tree_sitter/.
function(ensure_ts_headers version)
    set(ts_headers_dir "${GRAMMAR_DIR}/include/${version}/tree_sitter")
    file(MAKE_DIRECTORY "${ts_headers_dir}")

    set(required_headers
        parser.h
        array.h
        alloc.h
        atomic.h
        ts_assert.h
    )

    foreach(hdr ${required_headers})
        set(dst "${ts_headers_dir}/${hdr}")
        if(NOT EXISTS "${dst}")
            file(DOWNLOAD
                "https://raw.githubusercontent.com/tree-sitter/tree-sitter/v${version}/lib/src/${hdr}"
                "${dst}"
                STATUS status
                LOG log)
            list(GET status 0 rc)
            if(NOT rc EQUAL 0)
                # Fallback: search vcpkg buildtrees
                file(GLOB_RECURSE hdr_src
                    "${CMAKE_SOURCE_DIR}/vcpkg/buildtrees/tree-sitter*/src/v*/lib/src/${hdr}")
                list(GET hdr_src 0 hdr_src)
                if(hdr_src AND EXISTS "${hdr_src}")
                    file(COPY "${hdr_src}" DESTINATION "${ts_headers_dir}")
                endif()
            endif()
            if(NOT EXISTS "${dst}")
                message(WARNING "Cannot find tree_sitter/${hdr} v${version}")
            endif()
        endif()
    endforeach()
endfunction()

function(fetch_grammar name url ts_version)
    set(target "tsg-${name}")
    set(src_dir "${GRAMMAR_DIR}/${name}")

    # Ensure headers for this grammar's tree-sitter version
    ensure_ts_headers("${ts_version}")

    set(parser_src "${src_dir}/src/parser.c")
    if(NOT EXISTS "${parser_src}")
        message(STATUS "Fetching tree-sitter-${name} grammar from ${url}")
        file(DOWNLOAD "${url}/src/parser.c" "${parser_src}" STATUS status)
        list(GET status 0 rc)
        if(NOT rc EQUAL 0)
            message(WARNING "Failed to download tree-sitter-${name} parser.c")
            return()
        endif()

        # scanner.c (external lexer)
        file(DOWNLOAD "${url}/src/scanner.c" "${src_dir}/src/scanner.c" STATUS scanner_status)

        # Download extra files referenced by scanner.c (non-tree_sitter relative includes)
        # e.g., TypeScript grammars reference ../../common/scanner.h
        if(EXISTS "${src_dir}/src/scanner.c")
            file(READ "${src_dir}/src/scanner.c" scanner_content)
            string(REGEX MATCHALL "#include[ \t]*\"([^\"]+)\"" rel_includes "${scanner_content}")
            foreach(match ${rel_includes})
                string(REGEX REPLACE "#include[ \t]*\"([^\"]+)\"" "\\1" rel_path "${match}")
                # Skip tree_sitter/ includes — handled by ensure_ts_headers
                if(rel_path MATCHES "^tree_sitter/")
                    continue()
                endif()
                get_filename_component(abs_path "${src_dir}/src/${rel_path}" ABSOLUTE)
                file(RELATIVE_PATH rel_final "${src_dir}/src" "${abs_path}")
                file(DOWNLOAD "${url}/src/${rel_final}" "${abs_path}" STATUS extra_status)
            endforeach()
        endif()
    endif()

    # Collect source files
    set(sources "${parser_src}")
    if(EXISTS "${src_dir}/src/scanner.c")
        list(APPEND sources "${src_dir}/src/scanner.c")
    endif()

    add_library(${target} STATIC ${sources})
    target_include_directories(${target}
        PUBLIC "${src_dir}/src"
        PRIVATE "${GRAMMAR_DIR}/include/${ts_version}")
    target_compile_features(${target} PUBLIC c_std_11)
    set_target_properties(${target} PROPERTIES POSITION_INDEPENDENT_CODE ON)
endfunction()

# -- Grammars with their tree-sitter generator versions --
# JS v0.25.0 → needs parser.h from tree-sitter v0.25.x
fetch_grammar(javascript
    "https://raw.githubusercontent.com/tree-sitter/tree-sitter-javascript/v0.25.0"
    "0.25.2")

# TypeScript v0.23.2 → needs parser.h from tree-sitter v0.23.x
fetch_grammar(typescript
    "https://raw.githubusercontent.com/tree-sitter/tree-sitter-typescript/v0.23.2/typescript"
    "0.23.2")

# TSX v0.23.2 → needs parser.h from tree-sitter v0.23.x
fetch_grammar(tsx
    "https://raw.githubusercontent.com/tree-sitter/tree-sitter-typescript/v0.23.2/tsx"
    "0.23.2")

# Python v0.25.0 → needs parser.h from tree-sitter v0.25.x
fetch_grammar(python
    "https://raw.githubusercontent.com/tree-sitter/tree-sitter-python/v0.25.0"
    "0.25.2")

# Rust v0.23.2 → needs parser.h from tree-sitter v0.23.x
fetch_grammar(rust
    "https://raw.githubusercontent.com/tree-sitter/tree-sitter-rust/v0.23.2"
    "0.23.2")
